import '../presentation/search_map_screen/models/property_data.dart';

/// Shared demo inventory used when Supabase has no listings.
class PropertyCatalogDemo {
  static List<PropertyData> listings() {
    return _maps.map(PropertyData.fromMap).toList();
  }

  static const List<Map<String, dynamic>> _maps = [
    {
      'id': 'prop_001',
      'title': 'Modern Apartment — Karrada',
      'address': '14 Al-Nidhal St, Karrada, Baghdad',
      'price': 185000,
      'currency': 'USD',
      'area': 180,
      'bedrooms': 3,
      'bathrooms': 2,
      'type': 'apartment',
      'listingType': 'sale',
      'lat': 33.3152,
      'lng': 44.3932,
      'imageUrl':
          'https://images.unsplash.com/photo-1723709125265-889b7d62dcba',
      'semanticLabel': 'Modern apartment Karrada',
      'isVerified': true,
      'isFeatured': true,
      'tags': ['Furnished', 'Central AC', 'Parking', 'Elevator', 'Balcony'],
      'description':
          'شقة عصرية مفروشة في الكرادة قرب الجامعات والمستشفيات. موقف سيارة، تكييف مركزي، إطلالة شارع، مناسبة للعوائل الصغيرة والموظفين.',
      'nearbySchools': [
        'Baghdad College',
        'Al-Mansour Primary',
        'International School of Baghdad',
      ],
      'nearbyAmenities': [
        'Family Mall',
        'Al-Nahrain Hospital',
        'Tigris Corniche',
        'Cafes',
      ],
    },
    {
      'id': 'prop_002',
      'title': 'Villa — Mansour District',
      'address': '7 Prince Rd, Mansour, Baghdad',
      'price': 420000,
      'currency': 'USD',
      'area': 350,
      'bedrooms': 5,
      'bathrooms': 4,
      'type': 'villa',
      'listingType': 'sale',
      'lat': 33.3351,
      'lng': 44.3601,
      'imageUrl':
          'https://img.rocket.new/generatedImages/rocket_gen_img_15d2727d0-1784505971937.png',
      'semanticLabel': 'Villa Mansour',
      'isVerified': true,
      'isFeatured': false,
      'tags': ['Garden', 'Pool', 'Generator', 'Maid room', 'Garage'],
      'description':
          'فيلا واسعة في المنصور مع حديقة ومسبح ومولد وغرفة خادمة. حي راقٍ قريب من المدارس الخاصة والسفارات.',
      'nearbySchools': [
        'Mansour Private School',
        'Oxford International School',
      ],
      'nearbyAmenities': [
        'Al-Mansour Mall',
        'Ibn Sina Hospital',
        'Embassy district',
      ],
    },
    {
      'id': 'prop_003',
      'title': 'Office Space — Zayouna',
      'address': '22 Commerce Ave, Zayouna, Baghdad',
      'price': 2800,
      'currency': 'USD',
      'area': 120,
      'bedrooms': 0,
      'bathrooms': 2,
      'type': 'commercial',
      'listingType': 'rent',
      'lat': 33.3289,
      'lng': 44.4521,
      'imageUrl':
          'https://img.rocket.new/generatedImages/rocket_gen_img_181ce75b0-1780309836489.png',
      'semanticLabel': 'Office Zayouna',
      'isVerified': true,
      'isFeatured': true,
      'tags': ['Elevator', 'Backup Power', 'Reception', 'Meeting room'],
      'description':
          'مكتب تجاري للإيجار في زيونة مع استقبال ومصعد وطاقة احتياطية وغرفة اجتماعات. مناسب للشركات والعيادات.',
      'nearbySchools': ['Zayouna Secondary School'],
      'nearbyAmenities': ['Business center', 'Banks', 'Restaurants', 'Parking'],
    },
    {
      'id': 'prop_004',
      'title': 'Residential Land — Adhamiya',
      'address': 'Block 14, Adhamiya District, Baghdad',
      'price': 95000,
      'currency': 'USD',
      'area': 500,
      'bedrooms': 0,
      'bathrooms': 0,
      'type': 'land',
      'listingType': 'sale',
      'lat': 33.3712,
      'lng': 44.4089,
      'imageUrl':
          'https://img.rocket.new/generatedImages/rocket_gen_img_1b3327534-1772466446472.png',
      'semanticLabel': 'Land Adhamiya',
      'isVerified': false,
      'isFeatured': false,
      'tags': ['Corner Plot', 'Main Road Access', 'Investment'],
      'description':
          'قطعة أرض سكنية زاوية في الأعظمية مع واجهة على شارع رئيسي. مناسبة للبناء الاستثماري أو فيلا عائلية.',
      'nearbySchools': ['Adhamiya High School'],
      'nearbyAmenities': ['Local market', 'Mosque', 'Clinic'],
    },
    {
      'id': 'prop_005',
      'title': 'Townhouse — Jadriya',
      'address': '9 River View St, Jadriya, Baghdad',
      'price': 260000,
      'currency': 'USD',
      'area': 240,
      'bedrooms': 4,
      'bathrooms': 3,
      'type': 'villa',
      'listingType': 'mortgage',
      'lat': 33.2981,
      'lng': 44.3821,
      'imageUrl':
          'https://img.rocket.new/generatedImages/rocket_gen_img_151ea03e2-1786738383786.png',
      'semanticLabel': 'Townhouse Jadriya',
      'isVerified': true,
      'isFeatured': true,
      'tags': ['River View', 'Smart Home', 'Garage', 'Financing'],
      'description':
          'تاون هاوس بإطلالة نهر دجلة في الجادرية، منزل ذكي وكراج. متاح بتمويل عقاري للمشتري المؤهل.',
      'nearbySchools': [
        'University of Baghdad area schools',
        'Jadriya International School',
      ],
      'nearbyAmenities': ['Tigris promenade', 'Cafes', 'University campus'],
    },
    {
      'id': 'prop_006',
      'title': 'Apartment — Kadhimiya',
      'address': '33 Al-Kadhim St, Kadhimiya, Baghdad',
      'price': 75000,
      'currency': 'USD',
      'area': 110,
      'bedrooms': 2,
      'bathrooms': 1,
      'type': 'apartment',
      'listingType': 'sale',
      'lat': 33.3822,
      'lng': 44.3411,
      'imageUrl':
          'https://img.rocket.new/generatedImages/rocket_gen_img_1cbf890d9-1781368726031.png',
      'semanticLabel': 'Apartment Kadhimiya',
      'isVerified': false,
      'isFeatured': false,
      'tags': ['Near Metro', 'Quiet Area', 'Budget'],
      'description':
          'شقة اقتصادية هادئة في الكاظمية قرب النقل العام. خيار جيد للميزانيات المحدودة والمشترين لأول مرة.',
      'nearbySchools': ['Kadhimiya Primary School'],
      'nearbyAmenities': ['Metro stop', 'Local souq', 'Clinic'],
    },
    {
      'id': 'prop_007',
      'title': 'Duplex — Erbil Dream City',
      'address': 'Dream City, Erbil',
      'price': 310000,
      'currency': 'USD',
      'area': 280,
      'bedrooms': 4,
      'bathrooms': 3,
      'type': 'villa',
      'listingType': 'sale',
      'lat': 36.1911,
      'lng': 44.0092,
      'imageUrl':
          'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
      'semanticLabel': 'Duplex Erbil',
      'isVerified': true,
      'isFeatured': true,
      'tags': ['Compound', 'Security', 'Garden', 'Parking'],
      'description':
          'دوبلكس داخل مجمع محروس في أربيل مع حديقة وموقف. قريب من المدارس الدولية والمولات.',
      'nearbySchools': ['British International School Erbil', 'Classical School of the Medes'],
      'nearbyAmenities': ['Family Mall Erbil', 'Park', 'Gym'],
    },
    {
      'id': 'prop_008',
      'title': 'Studio Rent — Basra Corniche',
      'address': 'Corniche Rd, Basra',
      'price': 450,
      'currency': 'USD',
      'area': 55,
      'bedrooms': 1,
      'bathrooms': 1,
      'type': 'apartment',
      'listingType': 'rent',
      'lat': 30.5085,
      'lng': 47.7804,
      'imageUrl':
          'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
      'semanticLabel': 'Studio Basra',
      'isVerified': true,
      'isFeatured': false,
      'tags': ['Furnished', 'Sea breeze', 'Short lease'],
      'description':
          'استوديو مفروش للإيجار الشهري على كورنيش البصرة. مناسب للموظفين والزوار قصيري المدة.',
      'nearbySchools': ['Basra International School'],
      'nearbyAmenities': ['Corniche walk', 'Restaurants', 'Pharmacy'],
    },
    {
      'id': 'prop_009',
      'title': 'Commercial Shop — Najaf',
      'address': 'Old City edge, Najaf',
      'price': 160000,
      'currency': 'USD',
      'area': 90,
      'bedrooms': 0,
      'bathrooms': 1,
      'type': 'commercial',
      'listingType': 'sale',
      'lat': 31.995,
      'lng': 44.3147,
      'imageUrl':
          'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800',
      'semanticLabel': 'Shop Najaf',
      'isVerified': true,
      'isFeatured': false,
      'tags': ['Street front', 'High footfall', 'Retail'],
      'description':
          'محل تجاري بواجهة شارع في النجف، حركة مشاة عالية، مناسب للتجزئة أو الخدمات.',
      'nearbySchools': ['Najaf Secondary School'],
      'nearbyAmenities': ['Souq', 'Hotels', 'Transport hub'],
    },
    {
      'id': 'prop_010',
      'title': 'Family House — Mosul New',
      'address': 'New Mosul, Nineveh',
      'price': 135000,
      'currency': 'USD',
      'area': 200,
      'bedrooms': 3,
      'bathrooms': 2,
      'type': 'villa',
      'listingType': 'sale',
      'lat': 36.3489,
      'lng': 43.1578,
      'imageUrl':
          'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
      'semanticLabel': 'House Mosul',
      'isVerified': false,
      'isFeatured': true,
      'tags': ['New build', 'Parking', 'Quiet street'],
      'description':
          'بيت عائلي حديث البناء في الموصل الجديدة، شارع هادئ وموقف خاص، قريب من المدارس والخدمات.',
      'nearbySchools': ['Mosul Model School', 'Nineveh Private School'],
      'nearbyAmenities': ['Supermarket', 'Clinic', 'Park'],
    },
  ];
}
