import '../presentation/search_map_screen/models/property_data.dart';

/// Shared demo inventory used when Supabase has no listings.
class PropertyCatalogDemo {
  static List<PropertyData> listings() {
    return [..._maps, ..._governorateExtras].map((raw) {
      final map = Map<String, dynamic>.from(raw);
      map['title_ar'] ??= _arabicTitleFor(map);
      map['title_en'] ??= map['title'];
      map['title_ku'] ??= map['title_ar'] ?? map['title'];
      final district = map['district']?.toString() ?? '';
      map['address_ar'] ??= district.isEmpty ? map['address'] : '$district، العراق';
      map['address_en'] ??= map['address'];
      return PropertyData.fromMap(map);
    }).toList();
  }

  static String _arabicTitleFor(Map<String, dynamic> map) {
    final district = map['district']?.toString() ?? '';
    switch (map['id']) {
      case 'prop_001':
        return 'شقة عصرية — الكرادة';
      case 'prop_002':
        return 'فيلا — المنصور';
      case 'prop_003':
        return 'مكتب تجاري — زيونة';
      case 'prop_004':
        return 'أرض سكنية — الأعظمية';
      case 'prop_005':
        return 'تاون هاوس — الجادرية';
      case 'prop_006':
        return 'شقة — الكاظمية';
      case 'prop_007':
        return 'دوبلكس — أربيل';
      case 'prop_008':
        return 'استوديو للإيجار — البصرة';
      case 'prop_009':
        return 'محل تجاري — النجف';
      case 'prop_010':
        return 'بيت عائلي — الموصل';
      case 'prop_011':
        return 'بنتهاوس — الحارثية';
      case 'prop_012':
        return 'بيت عائلي — البياع';
      case 'prop_013':
        return 'استوديو — الكرادة';
      case 'prop_014':
        return 'محل — المنصور';
      case 'prop_015':
        return 'أرض زراعية — اليوسفية';
      case 'prop_016':
        return 'عمارة استثمارية — الكرادة';
      default:
        return '${map['title']} — $district';
    }
  }

  static const List<Map<String, dynamic>> _maps = [
    {
      'id': 'prop_001',
      'district': 'الكرادة',
      'builder_company': 'شركة الرشيد للإعمار',
      'year_built': 2019,
      'title': 'Modern Apartment — Karrada',
      'address': '14 Al-Nidhal St, Karrada, Baghdad',
      'price': 185000,
      'currency': 'USD',
      'area': 180,
      'bedrooms': 3,
      'bathrooms': 2,
      'type': 'apartment',
      'listingType': 'sale',
      'lat': 33.3152,
      'lng': 44.3932,
      'imageUrl':
          'https://images.unsplash.com/photo-1723709125265-889b7d62dcba',
      'semanticLabel': 'Modern apartment Karrada',
      'isVerified': true,
      'isFeatured': true,
      'tags': ['Furnished', 'Central AC', 'Parking', 'Elevator', 'Balcony'],
      'description':
          'شقة عصرية مفروشة في الكرادة قرب الجامعات والمستشفيات. موقف سيارة، تكييف مركزي، إطلالة شارع، مناسبة للعوائل الصغيرة والموظفين.',
      'nearbySchools': [
        'Baghdad College',
        'Al-Mansour Primary',
        'International School of Baghdad',
      ],
      'nearbyAmenities': [
        'Family Mall',
        'Al-Nahrain Hospital',
        'Tigris Corniche',
        'Cafes',
      ],
    },
    {
      'id': 'prop_002',
      'district': 'المنصور',
      'builder_company': 'مجموعة المهندس للبناء',
      'year_built': 2021,
      'title': 'Villa — Mansour District',
      'address': '7 Prince Rd, Mansour, Baghdad',
      'price': 420000,
      'currency': 'USD',
      'area': 350,
      'bedrooms': 5,
      'bathrooms': 4,
      'type': 'villa',
      'listingType': 'sale',
      'lat': 33.3351,
      'lng': 44.3601,
      'imageUrl':
          'https://img.rocket.new/generatedImages/rocket_gen_img_15d2727d0-1784505971937.png',
      'semanticLabel': 'Villa Mansour',
      'isVerified': true,
      'isFeatured': false,
      'tags': ['Garden', 'Pool', 'Generator', 'Maid room', 'Garage'],
      'description':
          'فيلا واسعة في المنصور مع حديقة ومسبح ومولد وغرفة خادمة. حي راقٍ قريب من المدارس الخاصة والسفارات.',
      'nearbySchools': [
        'Mansour Private School',
        'Oxford International School',
      ],
      'nearbyAmenities': [
        'Al-Mansour Mall',
        'Ibn Sina Hospital',
        'Embassy district',
      ],
    },
    {
      'id': 'prop_003',
      'district': 'زيونة',
      'builder_company': 'شركة الرافدين للمقاولات',
      'year_built': 2017,
      'title': 'Office Space — Zayouna',
      'address': '22 Commerce Ave, Zayouna, Baghdad',
      'price': 2800,
      'currency': 'USD',
      'area': 120,
      'bedrooms': 0,
      'bathrooms': 2,
      'type': 'commercial',
      'listingType': 'rent',
      'lat': 33.3289,
      'lng': 44.4521,
      'imageUrl':
          'https://img.rocket.new/generatedImages/rocket_gen_img_181ce75b0-1780309836489.png',
      'semanticLabel': 'Office Zayouna',
      'isVerified': true,
      'isFeatured': true,
      'tags': ['Elevator', 'Backup Power', 'Reception', 'Meeting room'],
      'description':
          'مكتب تجاري للإيجار في زيونة مع استقبال ومصعد وطاقة احتياطية وغرفة اجتماعات. مناسب للشركات والعيادات.',
      'nearbySchools': ['Zayouna Secondary School'],
      'nearbyAmenities': ['Business center', 'Banks', 'Restaurants', 'Parking'],
    },
    {
      'id': 'prop_004',
      'district': 'الأعظمية',
      'title': 'Residential Land — Adhamiya',
      'address': 'Block 14, Adhamiya District, Baghdad',
      'price': 95000,
      'currency': 'USD',
      'area': 500,
      'bedrooms': 0,
      'bathrooms': 0,
      'type': 'land',
      'listingType': 'sale',
      'lat': 33.3712,
      'lng': 44.4089,
      'imageUrl':
          'https://img.rocket.new/generatedImages/rocket_gen_img_1b3327534-1772466446472.png',
      'semanticLabel': 'Land Adhamiya',
      'isVerified': false,
      'isFeatured': false,
      'tags': ['Corner Plot', 'Main Road Access', 'Investment'],
      'description':
          'قطعة أرض سكنية زاوية في الأعظمية مع واجهة على شارع رئيسي. مناسبة للبناء الاستثماري أو فيلا عائلية.',
      'nearbySchools': ['Adhamiya High School'],
      'nearbyAmenities': ['Local market', 'Mosque', 'Clinic'],
    },
    {
      'id': 'prop_005',
      'district': 'الكاظمية',
      'builder_company': 'شركة بابل الحديثة',
      'year_built': 2022,
      'title': 'Townhouse — Jadriya',
      'address': '9 River View St, Jadriya, Baghdad',
      'price': 260000,
      'currency': 'USD',
      'area': 240,
      'bedrooms': 4,
      'bathrooms': 3,
      'type': 'villa',
      'listingType': 'mortgage',
      'lat': 33.2981,
      'lng': 44.3821,
      'imageUrl':
          'https://img.rocket.new/generatedImages/rocket_gen_img_151ea03e2-1786738383786.png',
      'semanticLabel': 'Townhouse Jadriya',
      'isVerified': true,
      'isFeatured': true,
      'tags': ['River View', 'Smart Home', 'Garage', 'Financing'],
      'description':
          'تاون هاوس بإطلالة نهر دجلة في الجادرية، منزل ذكي وكراج. متاح بتمويل عقاري للمشتري المؤهل.',
      'nearbySchools': [
        'University of Baghdad area schools',
        'Jadriya International School',
      ],
      'nearbyAmenities': ['Tigris promenade', 'Cafes', 'University campus'],
    },
    {
      'id': 'prop_006',
      'district': 'الدورة',
      'builder_company': 'مجموعة المهندس للبناء',
      'year_built': 2020,
      'title': 'Apartment — Kadhimiya',
      'address': '33 Al-Kadhim St, Kadhimiya, Baghdad',
      'price': 75000,
      'currency': 'USD',
      'area': 110,
      'bedrooms': 2,
      'bathrooms': 1,
      'type': 'apartment',
      'listingType': 'sale',
      'lat': 33.3822,
      'lng': 44.3411,
      'imageUrl':
          'https://img.rocket.new/generatedImages/rocket_gen_img_1cbf890d9-1781368726031.png',
      'semanticLabel': 'Apartment Kadhimiya',
      'isVerified': false,
      'isFeatured': false,
      'tags': ['Near Metro', 'Quiet Area', 'Budget'],
      'description':
          'شقة اقتصادية هادئة في الكاظمية قرب النقل العام. خيار جيد للميزانيات المحدودة والمشترين لأول مرة.',
      'nearbySchools': ['Kadhimiya Primary School'],
      'nearbyAmenities': ['Metro stop', 'Local souq', 'Clinic'],
    },
    {
      'id': 'prop_007',
      'district': 'الجادرية',
      'builder_company': 'شركة الرشيد للإعمار',
      'year_built': 2018,
      'title': 'Duplex — Erbil Dream City',
      'address': 'Dream City, Erbil',
      'price': 310000,
      'currency': 'USD',
      'area': 280,
      'bedrooms': 4,
      'bathrooms': 3,
      'type': 'villa',
      'listingType': 'sale',
      'lat': 36.1911,
      'lng': 44.0092,
      'imageUrl':
          'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
      'semanticLabel': 'Duplex Erbil',
      'isVerified': true,
      'isFeatured': true,
      'tags': ['Compound', 'Security', 'Garden', 'Parking'],
      'description':
          'دوبلكس داخل مجمع محروس في أربيل مع حديقة وموقف. قريب من المدارس الدولية والمولات.',
      'nearbySchools': ['British International School Erbil', 'Classical School of the Medes'],
      'nearbyAmenities': ['Family Mall Erbil', 'Park', 'Gym'],
    },
    {
      'id': 'prop_008',
      'district': 'المنصور',
      'builder_company': 'شركة النخبة العقارية',
      'year_built': 2023,
      'title': 'Studio Rent — Basra Corniche',
      'address': 'Corniche Rd, Basra',
      'price': 450,
      'currency': 'USD',
      'area': 55,
      'bedrooms': 1,
      'bathrooms': 1,
      'type': 'apartment',
      'listingType': 'rent',
      'lat': 30.5085,
      'lng': 47.7804,
      'imageUrl':
          'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
      'semanticLabel': 'Studio Basra',
      'isVerified': true,
      'isFeatured': false,
      'tags': ['Furnished', 'Sea breeze', 'Short lease'],
      'description':
          'استوديو مفروش للإيجار الشهري على كورنيش البصرة. مناسب للموظفين والزوار قصيري المدة.',
      'nearbySchools': ['Basra International School'],
      'nearbyAmenities': ['Corniche walk', 'Restaurants', 'Pharmacy'],
    },
    {
      'id': 'prop_009',
      'district': 'الكرادة',
      'title': 'Commercial Shop — Najaf',
      'address': 'Old City edge, Najaf',
      'price': 160000,
      'currency': 'USD',
      'area': 90,
      'bedrooms': 0,
      'bathrooms': 1,
      'type': 'commercial',
      'listingType': 'sale',
      'lat': 31.995,
      'lng': 44.3147,
      'imageUrl':
          'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800',
      'semanticLabel': 'Shop Najaf',
      'isVerified': true,
      'isFeatured': false,
      'tags': ['Street front', 'High footfall', 'Retail'],
      'description':
          'محل تجاري بواجهة شارع في النجف، حركة مشاة عالية، مناسب للتجزئة أو الخدمات.',
      'nearbySchools': ['Najaf Secondary School'],
      'nearbyAmenities': ['Souq', 'Hotels', 'Transport hub'],
    },
    {
      'id': 'prop_010',
      'district': 'زيونة',
      'builder_company': 'شركة بابل الحديثة',
      'year_built': 2016,
      'title': 'Family House — Mosul New',
      'address': 'New Mosul, Nineveh',
      'price': 135000,
      'currency': 'USD',
      'area': 200,
      'bedrooms': 3,
      'bathrooms': 2,
      'type': 'villa',
      'listingType': 'sale',
      'lat': 36.3489,
      'lng': 43.1578,
      'imageUrl':
          'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
      'semanticLabel': 'House Mosul',
      'isVerified': false,
      'isFeatured': true,
      'tags': ['New build', 'Parking', 'Quiet street'],
      'description':
          'بيت عائلي حديث البناء في الموصل الجديدة، شارع هادئ وموقف خاص، قريب من المدارس والخدمات.',
      'nearbySchools': ['Mosul Model School', 'Nineveh Private School'],
      'nearbyAmenities': ['Supermarket', 'Clinic', 'Park'],
    },
    {
      'id': 'prop_011',
      'district': 'الحارثية',
      'builder_company': 'شركة النخبة العقارية',
      'year_built': 2024,
      'title': 'Penthouse — Harthiya',
      'address': '12 Diplomat St, Harthiya, Baghdad',
      'price': 510000,
      'currency': 'USD',
      'area': 320,
      'bedrooms': 4,
      'bathrooms': 4,
      'type': 'apartment',
      'listingType': 'sale',
      'lat': 33.3128,
      'lng': 44.3554,
      'imageUrl':
          'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800',
      'semanticLabel': 'Penthouse Harthiya',
      'isVerified': true,
      'isFeatured': true,
      'tags': ['Penthouse', 'City view', 'Smart Home', 'Parking'],
      'description':
          'بنتهاوس فاخر في الحارثية بإطلالة مدينة، منزل ذكي ومواقف متعددة. مناسب للسكن الراقي والاستثمار.',
      'nearbySchools': ['Baghdad International School'],
      'nearbyAmenities': ['Hotels', 'Embassies', 'Cafes'],
    },
    {
      'id': 'prop_012',
      'district': 'البياع',
      'builder_company': 'شركة الرافدين للمقاولات',
      'year_built': 2015,
      'title': 'Family House — Bayaa',
      'address': 'Al-Bayaa, Baghdad',
      'price': 98000,
      'currency': 'USD',
      'area': 160,
      'bedrooms': 3,
      'bathrooms': 2,
      'type': 'villa',
      'listingType': 'sale',
      'lat': 33.2764,
      'lng': 44.3578,
      'imageUrl':
          'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800',
      'semanticLabel': 'House Bayaa',
      'isVerified': true,
      'isFeatured': false,
      'tags': ['Family', 'Parking', 'Near market'],
      'description':
          'بيت عائلي في البياع قرب السوق والخدمات، خيار عملي للسكن المستقر.',
      'nearbySchools': ['Bayaa Secondary School'],
      'nearbyAmenities': ['Souq', 'Clinic', 'Mosque'],
    },
    {
      'id': 'prop_013',
      'district': 'الكرادة',
      'builder_company': 'شركة الرشيد للإعمار',
      'year_built': 2020,
      'title': 'Studio — Karrada Inner',
      'address': 'Inner Karrada, Baghdad',
      'price': 650,
      'currency': 'USD',
      'area': 48,
      'bedrooms': 1,
      'bathrooms': 1,
      'type': 'apartment',
      'listingType': 'rent',
      'lat': 33.3089,
      'lng': 44.4011,
      'imageUrl':
          'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      'semanticLabel': 'Studio Karrada',
      'isVerified': true,
      'isFeatured': false,
      'tags': ['Furnished', 'Near cafes', 'Short lease'],
      'description':
          'استوديو مفروش في قلب الكرادة قرب المقاهي والجامعات. مناسب للطلاب والموظفين.',
      'nearbySchools': ['University of Baghdad'],
      'nearbyAmenities': ['Cafes', 'Malls', 'Clinics'],
    },
    {
      'id': 'prop_014',
      'district': 'المنصور',
      'builder_company': 'مجموعة المهندس للبناء',
      'year_built': 2018,
      'title': 'Retail Shop — Mansour',
      'address': '14 Ramadan St, Mansour, Baghdad',
      'price': 210000,
      'currency': 'USD',
      'area': 75,
      'bedrooms': 0,
      'bathrooms': 1,
      'type': 'commercial',
      'listingType': 'sale',
      'lat': 33.3312,
      'lng': 44.3688,
      'imageUrl':
          'https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=800',
      'semanticLabel': 'Shop Mansour',
      'isVerified': true,
      'isFeatured': true,
      'tags': ['Street front', 'Retail', 'High traffic'],
      'description':
          'محل تجاري بواجهة شارع في المنصور، حركة عالية ومناسب للعلامات التجارية.',
      'nearbySchools': ['Mansour Private School'],
      'nearbyAmenities': ['Al-Mansour Mall', 'Banks', 'Restaurants'],
    },
    {
      'id': 'prop_015',
      'district': 'اليوسفية',
      'title': 'Agricultural Land — Yusufiyah',
      'address': 'Yusufiyah, Baghdad belt',
      'price': 220000,
      'currency': 'USD',
      'area': 4000,
      'bedrooms': 0,
      'bathrooms': 0,
      'type': 'agricultural',
      'listingType': 'sale',
      'lat': 33.148,
      'lng': 44.252,
      'imageUrl':
          'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800',
      'semanticLabel': 'Agricultural land Yusufiyah',
      'isVerified': true,
      'isFeatured': false,
      'tags': ['Agricultural', 'Irrigation', 'Investment'],
      'description':
          'أرض زراعية في اليوسفية مع حصة ماء، مناسبة للبساتين أو التحويل لاحقاً.',
      'nearbySchools': ['Yusufiyah School'],
      'nearbyAmenities': ['Canal', 'Village market'],
    },
    {
      'id': 'prop_016',
      'district': 'الكرادة',
      'builder_company': 'شركة الرشيد للإعمار',
      'year_built': 2014,
      'title': 'Investment Building — Karrada',
      'address': 'Inner Karrada, Baghdad',
      'price': 890000,
      'currency': 'USD',
      'area': 620,
      'bedrooms': 12,
      'bathrooms': 8,
      'type': 'building',
      'listingType': 'investment',
      'lat': 33.3022,
      'lng': 44.412,
      'imageUrl':
          'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800',
      'semanticLabel': 'Investment building Karrada',
      'isVerified': true,
      'isFeatured': true,
      'tags': ['Investment', 'Elevator', 'Rented units'],
      'description':
          'عمارة استثمارية في الكرادة بعدة شقق مؤجرة، عائد شهري مناسب للمستثمر.',
      'nearbySchools': ['Baghdad College'],
      'nearbyAmenities': ['Cafes', 'Banks', 'Mall'],
    },
  ];

  static const List<Map<String, dynamic>> _governorateExtras = [
    {
      'id': 'prop_017',
      'district': 'كركوك',
      'title': 'Family House — Kirkuk',
      'address': 'Kirkuk city center',
      'price': 145000,
      'currency': 'USD',
      'area': 210,
      'bedrooms': 4,
      'bathrooms': 3,
      'type': 'villa',
      'listingType': 'sale',
      'lat': 35.4681,
      'lng': 44.3922,
      'imageUrl': 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800',
      'semanticLabel': 'House Kirkuk',
      'isVerified': true,
      'isFeatured': false,
      'tags': ['Garden', 'Parking', 'Generator'],
      'description': 'بيت عائلي في كركوك مع حديقة وموقف ومولد.',
      'nearbySchools': ['Kirkuk Secondary'],
      'nearbyAmenities': ['Hospital', 'Mosque', 'Market'],
    },
    {
      'id': 'prop_018',
      'district': 'الرمادي',
      'title': 'Apartment — Ramadi',
      'address': 'Ramadi, Anbar',
      'price': 72000,
      'currency': 'USD',
      'area': 140,
      'bedrooms': 3,
      'bathrooms': 2,
      'type': 'apartment',
      'listingType': 'sale',
      'lat': 33.4258,
      'lng': 43.2992,
      'imageUrl': 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
      'semanticLabel': 'Apartment Ramadi',
      'isVerified': true,
      'isFeatured': false,
      'tags': ['Furnished', 'Balcony'],
      'description': 'شقة في الرمادي، الأنبار.',
      'nearbySchools': ['Ramadi School'],
      'nearbyAmenities': ['Mosque', 'Park'],
    },
    {
      'id': 'prop_019',
      'district': 'كربلاء',
      'title': 'Hotel apartment — Karbala',
      'address': 'Karbala, Iraq',
      'price': 210000,
      'currency': 'USD',
      'area': 165,
      'bedrooms': 2,
      'bathrooms': 2,
      'type': 'apartment',
      'listingType': 'investment',
      'lat': 32.6160,
      'lng': 44.0249,
      'imageUrl': 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      'semanticLabel': 'Karbala investment',
      'isVerified': true,
      'isFeatured': true,
      'tags': ['Elevator', 'Furnished', 'Security'],
      'description': 'شقة استثمارية قرب الحرم في كربلاء.',
      'nearbySchools': ['Karbala School'],
      'nearbyAmenities': ['Mosque', 'Mall', 'Hospital'],
    },
    {
      'id': 'prop_020',
      'district': 'الحلة',
      'title': 'Villa — Hilla',
      'address': 'Hilla, Babil',
      'price': 198000,
      'currency': 'USD',
      'area': 280,
      'bedrooms': 5,
      'bathrooms': 4,
      'type': 'villa',
      'listingType': 'sale',
      'lat': 32.4833,
      'lng': 44.4333,
      'imageUrl': 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800',
      'semanticLabel': 'Villa Hilla',
      'isVerified': true,
      'isFeatured': false,
      'tags': ['Garden', 'Pool', 'Garage'],
      'description': 'فيلا في الحلة، بابل.',
      'nearbySchools': ['Babil School'],
      'nearbyAmenities': ['Park', 'Hospital'],
    },
    {
      'id': 'prop_021',
      'district': 'الكوت',
      'title': 'Land — Kut',
      'address': 'Kut, Wasit',
      'price': 55000,
      'currency': 'USD',
      'area': 800,
      'bedrooms': 0,
      'bathrooms': 0,
      'type': 'land',
      'listingType': 'sale',
      'lat': 32.5128,
      'lng': 45.8180,
      'imageUrl': 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800',
      'semanticLabel': 'Land Kut',
      'isVerified': false,
      'isFeatured': false,
      'tags': ['Residential plot'],
      'description': 'قطعة أرض سكنية في الكوت، واسط.',
      'nearbySchools': ['Wasit School'],
      'nearbyAmenities': ['Market'],
    },
    {
      'id': 'prop_022',
      'district': 'بعقوبة',
      'title': 'House — Baqubah',
      'address': 'Baqubah, Diyala',
      'price': 88000,
      'currency': 'USD',
      'area': 190,
      'bedrooms': 4,
      'bathrooms': 2,
      'type': 'villa',
      'listingType': 'sale',
      'lat': 33.7446,
      'lng': 44.6435,
      'imageUrl': 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800',
      'semanticLabel': 'House Baqubah',
      'isVerified': true,
      'isFeatured': false,
      'tags': ['Garden', 'Generator'],
      'description': 'بيت في بعقوبة، ديالى.',
      'nearbySchools': ['Diyala School'],
      'nearbyAmenities': ['Hospital', 'Mosque'],
    },
    {
      'id': 'prop_023',
      'district': 'تكريت',
      'title': 'Apartment — Tikrit',
      'address': 'Tikrit, Saladin',
      'price': 64000,
      'currency': 'USD',
      'area': 125,
      'bedrooms': 3,
      'bathrooms': 2,
      'type': 'apartment',
      'listingType': 'rent',
      'lat': 34.5967,
      'lng': 43.6786,
      'imageUrl': 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800',
      'semanticLabel': 'Apartment Tikrit',
      'isVerified': true,
      'isFeatured': false,
      'tags': ['Parking', 'Balcony'],
      'description': 'شقة للإيجار في تكريت، صلاح الدين.',
      'nearbySchools': ['Tikrit University'],
      'nearbyAmenities': ['Mosque', 'Park'],
    },
    {
      'id': 'prop_024',
      'district': 'الناصرية',
      'title': 'Shop — Nasiriyah',
      'address': 'Nasiriyah, Dhi Qar',
      'price': 41000,
      'currency': 'USD',
      'area': 90,
      'bedrooms': 0,
      'bathrooms': 1,
      'type': 'commercial',
      'listingType': 'sale',
      'lat': 31.0521,
      'lng': 46.2573,
      'imageUrl': 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800',
      'semanticLabel': 'Shop Nasiriyah',
      'isVerified': true,
      'isFeatured': false,
      'tags': ['Street front'],
      'description': 'محل تجاري في الناصرية، ذي قار.',
      'nearbySchools': ['Dhi Qar School'],
      'nearbyAmenities': ['Mall', 'Mosque'],
    },
    {
      'id': 'prop_025',
      'district': 'العمارة',
      'title': 'House — Amarah',
      'address': 'Amarah, Maysan',
      'price': 76000,
      'currency': 'USD',
      'area': 200,
      'bedrooms': 4,
      'bathrooms': 3,
      'type': 'villa',
      'listingType': 'mortgage',
      'lat': 31.8356,
      'lng': 47.1444,
      'imageUrl': 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
      'semanticLabel': 'House Amarah',
      'isVerified': true,
      'isFeatured': false,
      'tags': ['Garden', 'Parking'],
      'description': 'بيت برهن في العمارة، ميسان.',
      'nearbySchools': ['Maysan School'],
      'nearbyAmenities': ['Hospital', 'Park'],
    },
    {
      'id': 'prop_026',
      'district': 'السماوة',
      'title': 'Land — Samawah',
      'address': 'Samawah, Muthanna',
      'price': 38000,
      'currency': 'USD',
      'area': 1200,
      'bedrooms': 0,
      'bathrooms': 0,
      'type': 'land',
      'listingType': 'sale',
      'lat': 31.3160,
      'lng': 45.2806,
      'imageUrl': 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800',
      'semanticLabel': 'Land Samawah',
      'isVerified': false,
      'isFeatured': false,
      'tags': ['Agricultural'],
      'description': 'أرض في السماوة، المثنى.',
      'nearbySchools': ['Muthanna School'],
      'nearbyAmenities': ['Market'],
    },
    {
      'id': 'prop_027',
      'district': 'الديوانية',
      'title': 'Apartment — Diwaniyah',
      'address': 'Diwaniyah, Al-Qadisiyyah',
      'price': 69000,
      'currency': 'USD',
      'area': 155,
      'bedrooms': 3,
      'bathrooms': 2,
      'type': 'apartment',
      'listingType': 'sale',
      'lat': 31.9892,
      'lng': 44.9249,
      'imageUrl': 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
      'semanticLabel': 'Apartment Diwaniyah',
      'isVerified': true,
      'isFeatured': false,
      'tags': ['Elevator', 'Parking'],
      'description': 'شقة في الديوانية، القادسية.',
      'nearbySchools': ['Qadisiyyah School'],
      'nearbyAmenities': ['Mall', 'Hospital'],
    },
    {
      'id': 'prop_028',
      'district': 'السليمانية',
      'title': 'Penthouse — Sulaymaniyah',
      'address': 'Sulaymaniyah, Kurdistan',
      'price': 310000,
      'currency': 'USD',
      'area': 240,
      'bedrooms': 4,
      'bathrooms': 3,
      'type': 'apartment',
      'listingType': 'sale',
      'lat': 35.5558,
      'lng': 45.4351,
      'imageUrl': 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800',
      'semanticLabel': 'Penthouse Sulaymaniyah',
      'isVerified': true,
      'isFeatured': true,
      'tags': ['Furnished', 'Elevator', 'Security', 'Balcony'],
      'description': 'بنتهاوس في السليمانية.',
      'nearbySchools': ['Sulaymaniyah International'],
      'nearbyAmenities': ['Mall', 'Park', 'Hospital'],
    },
    {
      'id': 'prop_029',
      'district': 'دهوك',
      'title': 'Villa — Duhok',
      'address': 'Duhok, Kurdistan',
      'price': 265000,
      'currency': 'USD',
      'area': 320,
      'bedrooms': 5,
      'bathrooms': 4,
      'type': 'villa',
      'listingType': 'sale',
      'lat': 36.8671,
      'lng': 42.9884,
      'imageUrl': 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
      'semanticLabel': 'Villa Duhok',
      'isVerified': true,
      'isFeatured': false,
      'tags': ['Garden', 'Pool', 'Garage', 'Generator'],
      'description': 'فيلا في دهوك.',
      'nearbySchools': ['Duhok School'],
      'nearbyAmenities': ['Mall', 'Park'],
    },
  ];
}
